# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test
  displayName: 'dotnet test'
- script: dotnet publish --configuration $(buildConfiguration) -r $(runtime)
  displayName: 'dotnet publish $(buildConfiguration) $(runtime)'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub (janssenio)'
    repository: 'janssenio/amintiri'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.SourceBranchName)-latest
      $(Build.SourceBranchName)-$(Build.BuildId)
