# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test
  displayName: 'dotnet test'
- script: dotnet publish --configuration $(buildConfiguration) -r $(runtime)
  displayName: 'dotnet publish $(buildConfiguration) $(runtime)'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub (janssenio)'
    repository: 'janssenio/amintiri'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.SourceBranchName)-latest
      $(Build.SourceBranchName)-$(Build.BuildId)
- task: CopyFiles@2
  inputs:
    Contents: '**/docker-compose.yml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "$(Build.SourceBranchName)-$(Build.BuildId)" > $(Build.ArtifactStagingDirectory)/tag'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'amintiri'
    publishLocation: 'Container'

