version: '2.0'

services:
    postgres:
        image: postgres
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: amintiri
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: amintiri
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 15081:8080
    amintiri:
        image: janssenio/amintiri:${AMINTIRI_TAG}
        depends_on: 
            - postgres
        restart: unless-stopped
        ports:
            - 30000:80
        environment:
            postgres__password: ${POSTGRES_PASSWORD}
            authorization__appkey: ${APPKEY}
