version: '2'

services:
    postgres:
        image: postgres
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: amintiri
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
            POSTGRES_DB: amintiri
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 15081:8080
    amintiri:
        image: janssenio/amintiri:${AMINTIRI_TAG}
        restart: unless-stopped
        ports:
            - 30000:80
        environment:
            postgres_password: ${POSTGRES_PASS}
